services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    environment:
      - DEBUG=True
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - dev-network
    volumes:
      - ./src:/app

networks:
  dev-network:
    driver: bridge
